name: CI - Test and Build Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: game
      FRONTEND_PORT: 3000
      API_PORT: 8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Black for formatting check
        run: |
          python -m pip install --upgrade pip
          pip install black==25.1.0

      - name: Run Black formatting check
        run: black --check rpsls_game_api/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env


      - name: Build and Start Docker Containers
        run: docker compose up -d --build
        env:
          DB_USER: user
          DB_PASSWORD: password
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: game
          FRONTEND_PORT: 3000
          API_PORT: 8000

      - name: Wait for API to be healthy
        run: |
          for i in {1..10}; do
            curl --fail http://localhost:8000/health && break || sleep 5
          done

      - name: Install API test dependencies
        run: |
          pip install -r rpsls_game_api/requirements.txt

      - name: Run Pytest (backend tests)
        working-directory: rpsls_game_api
        run: pytest

      - name: Test API Health Endpoint
        run: curl http://localhost:8000/health

      - name: Shut down containers
        run: docker compose down
